title: Timothy Muppidi
description: >- 
  Welcome to my portfolio! I’m a [Timothy Muppidi], I am currently pursuing a Bachelor of Technology in Computer Science Engineering at Lovely Professional University. 
  As a resourceful and dedicated student, I am passionate about developing my technical skills and expanding my knowledge in the field of cybersecurity.
theme: jekyll-theme-hacker
