title: Timothy Muppidi
logo: assets/img/portfolio images
description: >- 
  Welcome to my portfolio! I’m a [Timothy Muppidi], I am currently pursuing a Bachelor of Technology in Computer Science Engineering at Lovely Professional University. 
  As a resourceful and dedicated student, I am passionate about developing my technical skills and expanding my knowledge in the field of cybersecurity.
theme: jekyll-theme-hacker
profile_picture: /assets/img/profile.jpg
social_links:
  github: https://github.com/timothy1240
  linkedin: https://www.linkedin.com/in/timothy-muppidi
